#!/usr/bin/env node

/**
 * Refreshes the benchmark tables between the BENCH markers in README.md and
 * every markdown file under docs/. Called by .github/workflows/benchmark.yml
 * with fresh results on each pull request; can also be run locally:
 *
 *   node benchmarks/benchmark.js --json > bench.json
 *   node scripts/update-readme.js bench.json
 */

const fs = require('node:fs');
const path = require('node:path');

const START_MARKER = '<!-- BENCH:START -->';
const END_MARKER = '<!-- BENCH:END -->';

const benchPath = process.argv[2] || 'bench.json';

function fail(message) {
	console.error(`update-readme: ${message}`);
	process.exit(1);
}

let bench;
try {
	bench = JSON.parse(fs.readFileSync(benchPath, 'utf8'));
} catch (error) {
	fail(`cannot read ${benchPath}: ${error.message}`);
}
if (!bench || !bench.meta || !Array.isArray(bench.results) || bench.results.length === 0) {
	fail(`${benchPath} does not look like benchmark output (expected { meta, results[] })`);
}

function buildBlock() {
	const { meta } = bench;
	const lines = [
		START_MARKER,
		'<!-- Auto-generated by scripts/update-readme.js — do not edit by hand -->',
		'',
		`_Node ${meta.node} · ${meta.cpu} · ${meta.platform} · ${meta.date} — refreshed automatically by the \`Update README benchmarks\` workflow._`,
		'',
		'| Operation | ops/sec | ns/op |',
		'|-----------|--------:|------:|',
	];
	for (const r of bench.results) {
		lines.push(`| ${r.name} | ${r.opsPerSec.toLocaleString('en-US')} | ${r.nsPerOp.toLocaleString('en-US')} |`);
	}
	lines.push(END_MARKER);
	return lines.join('\n');
}

function collectTargets() {
	const targets = ['README.md'];
	if (fs.existsSync('docs')) {
		for (const file of fs.readdirSync('docs')) {
			if (file.endsWith('.md')) {
				targets.push(path.join('docs', file));
			}
		}
	}
	return targets;
}

const block = buildBlock();
let updated = 0;

for (const target of collectTargets()) {
	if (!fs.existsSync(target)) {
		continue;
	}
	const content = fs.readFileSync(target, 'utf8');
	const startIndex = content.indexOf(START_MARKER);
	const endIndex = content.indexOf(END_MARKER);
	if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
		console.error(`update-readme: no BENCH markers in ${target}, skipped`);
		continue;
	}
	const next = content.slice(0, startIndex) + block + content.slice(endIndex + END_MARKER.length);
	if (next !== content) {
		fs.writeFileSync(target, next);
		console.log(`update-readme: refreshed ${target}`);
	} else {
		console.log(`update-readme: ${target} already up to date`);
	}
	updated++;
}

if (updated === 0) {
	fail('no file contained BENCH markers — wiring is broken');
}
